### ISSUE TITLE
RNNLogic_integrate

### ISSUE THREAD

**Issue by lijun-1999** [dair-iitd/KGC-Ensemble#3]
Traceback (most recent call last):
  File "script/run.py", line 17, in <module>
    from nbfnet import tasks, util
  File "/root/autodl-tmp/Sim-RotatE/NBFNet/nbfnet/util.py", line 17, in <module>
    from RNNLogic_integrate import get_WN_mappings
ModuleNotFoundError: No module named 'RNNLogic_integrate'

Hello, teacher, our current research direction is the completion of knowledge graph. Intensive reading teacher wants to reproduce your paper, but now I encounter this problem, and I want to ask the teacher how to solve it.

**Comment by uyey124** [comment]
可能……是from integrate import get_WN_mappings？

**Comment by mobius10** [comment]
> 可能……是from integrate import get_WN_mappings？

但这么改就会缺少两个参数，报错如下：
Traceback (most recent call last):
  File "script/run.py", line 17, in <module>
    from nbfnet import tasks, util
  File "/data1/zifeng/KGC-Ensemble-main/NBFNet/nbfnet/util.py", line 24, in <module>
    nbf2rnnent, nbf2rnnrel, _, _ = get_WN_mappings()
TypeError: get_WN_mappings() missing 2 required positional arguments: 'dataset' and 'root'

**Comment by mobius10** [comment]
> 可能……是from integrate import get_WN_mappings？

所以到底是要如何修改？
如果改为from integrate import get_WN_mappings，报错如下：
Traceback (most recent call last):
File "script/run.py", line 17, in
from nbfnet import tasks, util
File "/data1/zifeng/KGC-Ensemble-main/NBFNet/nbfnet/util.py", line 24, in
nbf2rnnent, nbf2rnnrel, _, _ = get_WN_mappings()
TypeError: get_WN_mappings() missing 2 required positional arguments: 'dataset' and 'root'
